# Google Cloud Run deployment configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dispatch-webcrawl-scraper
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "3"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1000m"
    spec:
      serviceAccountName: scraper-service-account
      containers:
        - image: gcr.io/PROJECT_ID/dispatch-webcrawl-scraper:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: HEADLESS
              value: "true"
            - name: LOG_LEVEL
              value: "info"
            - name: HEALTH_CHECK_PORT
              value: "8080"
            - name: CHROME_CDP_URL
              value: "http://chrome-service:3000"
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10

---
# Chrome browser service for Playwright
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chrome-service
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "2"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1000m"
    spec:
      containers:
        - image: browserless/chrome:latest
          ports:
            - containerPort: 3000
          env:
            - name: CONCURRENT
              value: "1"
            - name: TOKEN
              value: "your-security-token-here"
            - name: ENABLE_DEBUGGER
              value: "true"
            - name: MAX_CONCURRENT_SESSIONS
              value: "1"
            - name: KEEP_ALIVE
              value: "true"
            - name: PREBOOT_CHROME
              value: "true"
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10

---
# Service Account for the scraper
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scraper-service-account
  annotations:
    iam.gke.io/gcp-service-account: scraper-gsa@PROJECT_ID.iam.gserviceaccount.com
